=head1 NAME

vdrpbd.conf - Configuration file for vdrpbd

=head1 SYNOPSIS

B<vdrpbd.conf>

=head1 DESCRIPTION

The file B<vdrpbd.conf> is an optional configuration file to customize some settings of vdrpbd. It is normally located in the /etc directory.

=head1 VARIABLES

The following variables can be set in vdrpbd.conf:

 ER_COUNT=4
 ER_TIME=3

=over 5

These two variables customize the key sequence that has to be pressed to trigger an emergency reboot. The variable "ER_TIME" sets the time range in seconds, in which you have to press the power button "ER_COUNT" times.

=back

 TARGET=svdrp

=over 5

This allows you to define the target for the power button event. Default is B<svdrp> for sending to a running VDR daemon using the SVDRP protocol. Set to B<dbus> to send to VDR via dbus. This requires the dbus2vdr plugin to be loaded in VDR and the "Net::DBus" Perl module has to exist on your system. Set to B<kodi> to send to a running Kodi process via TCP.

=back

=head1 SEE ALSO

vdrpbd(1)
